Version 1.9.3 ❄️
AnacondaRecipes/typish-feedstock pull request #2
Opened 2023-12-04 23:21 UTC by SC426

2023-12-04 23:56 UTC, ryanskeith approved these changes
LGTM

2023-12-05 00:12 UTC, lorepirri commented
@SC426 could you please reactivate the CI? the build/checks were not triggered (remove `[skip ci]` from the title)

2023-12-05 00:13 UTC, lorepirri commented
[PKG-3567]

2023-12-05 00:17 UTC, lorepirri approved these changes
LGTM, thanks!

2023-12-05 16:42 UTC, lorepirri commented
@SC426  

- you could add a branch protection rule requiring two reviewers here (for `main`): https://github.com/AnacondaRecipes/typish-feedstock/settings/branches

- and check the `Automatically delete head branches ` here: https://github.com/AnacondaRecipes/typish-feedstock/settings

- please next time the ticket number either in the description (possibly), either in the branch name

2023-12-05 19:14 UTC, JeanChristopheMorinPerso requested changes

2023-12-05 19:14 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - wheel
```suggestion
    - wheel
    - setuptools
```

2023-12-11 11:14 UTC, M-Waszkiewicz-Anaconda approved these changes
LGTM

2023-12-11 14:21 UTC, closed without merging